"""upd foreign key fields

Revision ID: 69b375ded1a6
Revises: 4c5184fb6963
Create Date: 2023-06-13 17:29:12.369229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69b375ded1a6'
down_revision = '4c5184fb6963'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_user_id_fkey', 'comment', type_='foreignkey')
    op.drop_constraint('comment_parent_id_fkey', 'comment', type_='foreignkey')
    op.drop_constraint('comment_video_id_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'comment', ['parent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comment', 'video', ['video_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('like_video_id_fkey', 'like', type_='foreignkey')
    op.drop_constraint('like_user_id_fkey', 'like', type_='foreignkey')
    op.create_foreign_key(None, 'like', 'video', ['video_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'like', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('subscriptions_user_fkey', 'subscriptions', type_='foreignkey')
    op.drop_constraint('subscriptions_subscribed_to_fkey', 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'user', ['user'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'subscriptions', 'user', ['subscribed_to'], ['id'], ondelete='CASCADE')
    op.drop_constraint('video_author_id_fkey', 'video', type_='foreignkey')
    op.create_foreign_key(None, 'video', 'user', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video', type_='foreignkey')
    op.create_foreign_key('video_author_id_fkey', 'video', 'user', ['author_id'], ['id'])
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key('subscriptions_subscribed_to_fkey', 'subscriptions', 'user', ['subscribed_to'], ['id'])
    op.create_foreign_key('subscriptions_user_fkey', 'subscriptions', 'user', ['user'], ['id'])
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.create_foreign_key('like_user_id_fkey', 'like', 'user', ['user_id'], ['id'])
    op.create_foreign_key('like_video_id_fkey', 'like', 'video', ['video_id'], ['id'])
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_video_id_fkey', 'comment', 'video', ['video_id'], ['id'])
    op.create_foreign_key('comment_parent_id_fkey', 'comment', 'comment', ['parent_id'], ['id'])
    op.create_foreign_key('comment_user_id_fkey', 'comment', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
