"""upd video model

Revision ID: a89fa9bda247
Revises: c4dfaf76fb4c
Create Date: 2023-06-13 09:50:10.785852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a89fa9bda247'
down_revision = 'c4dfaf76fb4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('video', sa.Column('file', sa.String(), nullable=False))
    op.drop_column('video', 'url')
    op.drop_column('video', 'views')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('views', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('video', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('video', 'file')
    op.drop_column('video', 'name')
    # ### end Alembic commands ###
