"""initial

Revision ID: c4dfaf76fb4c
Revises: a5d5b7b17055
Create Date: 2023-05-11 11:50:27.919896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4dfaf76fb4c'
down_revision = 'a5d5b7b17055'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('like_comment_id_fkey', 'like', type_='foreignkey')
    op.drop_column('like', 'comment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like', sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('like_comment_id_fkey', 'like', 'comment', ['comment_id'], ['id'])
    # ### end Alembic commands ###
